theme: jekyll-theme-slate

title: Participatory Design Toolkit V2
# baseurl: "https://padlad.github.io/Participatory-Design-ToolkitV2/"
# url: "https://padlad.github.io/Participatory-Design-ToolkitV2/"

# build settings
